[package]
name = "trs_24"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
winit = { version = "0.28.7", features = ["android-native-activity"] }
# My personal glutin fork that includes a GLES2 patch (Will replace once merged to main repo)
glutin = { git = "https://github.com/p0ryae/glutin" }
raw-window-handle = "0.5.0"
android_logger = "0.13.3"
stb_image_rust = "2.27.2"
nalgebra-glm = "0.18.0"
json = "0.12.4"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.1.1"

[lib]
name = "trs_24"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 1
strip = true