[package]
name = "trs_24"
version = "0.1.2"
edition = "2021"
keywords = ["gamedev", "graphics", "android", "trs_24", "engine"]
license = "MIT OR Apache-2.0"
description = "An OpenGL-Powered Android Game Engine"
repository = "https://github.com/p0ryae/TRS_24"
exclude = [
    "assets/*",
    "android/*"
]

[dependencies]
log = "0.4"
winit = { version = "0.28.7", features = ["android-native-activity"] }
# My personal glutin fork that includes a GLES2 patch
# Will replace this with the main repo once my purposed change is merged (See https://github.com/rust-windowing/glutin/pull/1648).
glutin = { git = "https://github.com/p0ryae/glutin", version = "0.31.1" }
raw-window-handle = "0.5.0"
android_logger = "0.13.3"
stb_image_rust = "2.27.2"
nalgebra-glm = "0.18.0"
json = "0.12.4"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.1.1"
